# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean spring-boot:build-image --batch-mode --no-transfer-progress --file pom.xml

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker tag docker.io/library/server docker.io/${{ secrets.DOCKER_USERNAME }}/server:latest
          docker tag docker.io/library/server docker.io/${{ secrets.DOCKER_USERNAME }}/server:${{ steps.vars.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/server
