# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean spring-boot:build-image --batch-mode --no-transfer-progress --file pom.xml

      - uses: azure/docker-login@v1
        with:
          login-server: 'index.docker.io'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker tag server:latest ${{ secrets.DOCKER_USERNAME }}/server:$GITHUB_REF
          docker push ${{ secrets.DOCKER_USERNAME }}/server:$GITHUB_REF
